//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTopper.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnTopper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable on startup.
        /// </summary>
        internal static string EN_ADD_AUTORUN {
            get {
                return ResourceManager.GetString("EN_ADD_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added to autorun.
        /// </summary>
        internal static string EN_ADDED_AUTORUN {
            get {
                return ResourceManager.GetString("EN_ADDED_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTopper.
        /// </summary>
        internal static string EN_APP_NAME {
            get {
                return ResourceManager.GetString("EN_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autorun.
        /// </summary>
        internal static string EN_AUTORUN {
            get {
                return ResourceManager.GetString("EN_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string EN_CLOSE {
            get {
                return ResourceManager.GetString("EN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dont enable on startup.
        /// </summary>
        internal static string EN_DELETE_AUTORUN {
            get {
                return ResourceManager.GetString("EN_DELETE_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted from autorun.
        /// </summary>
        internal static string EN_DELETED_AUTORUN {
            get {
                return ResourceManager.GetString("EN_DELETED_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string EN_ERROR {
            get {
                return ResourceManager.GetString("EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide in taskbar.
        /// </summary>
        internal static string EN_HIDE_IN_TASKBAR {
            get {
                return ResourceManager.GetString("EN_HIDE_IN_TASKBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTopper minimized.
        /// </summary>
        internal static string EN_MINIMIZED {
            get {
                return ResourceManager.GetString("EN_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTopper has been minimized, right click on the icon below to open.
        /// </summary>
        internal static string EN_MINIMIZED_RIGHT_CLICK {
            get {
                return ResourceManager.GetString("EN_MINIMIZED_RIGHT_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New version available, update now?.
        /// </summary>
        internal static string EN_NEW_VERSION_AVAILABLE_QUESTION {
            get {
                return ResourceManager.GetString("EN_NEW_VERSION_AVAILABLE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No update available.
        /// </summary>
        internal static string EN_NO_UPDATE {
            get {
                return ResourceManager.GetString("EN_NO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string EN_OPEN {
            get {
                return ResourceManager.GetString("EN_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process doesn&apos;t exists anymore.
        /// </summary>
        internal static string EN_PROCESS_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("EN_PROCESS_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select process first.
        /// </summary>
        internal static string EN_SELECT_PROCESS {
            get {
                return ResourceManager.GetString("EN_SELECT_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please set window height and width.
        /// </summary>
        internal static string EN_SET_HEIGHT_WIDTH {
            get {
                return ResourceManager.GetString("EN_SET_HEIGHT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set this.
        /// </summary>
        internal static string EN_SET_THIS {
            get {
                return ResourceManager.GetString("EN_SET_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set top.
        /// </summary>
        internal static string EN_SET_TOP {
            get {
                return ResourceManager.GetString("EN_SET_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unset this.
        /// </summary>
        internal static string EN_UNSET_THIS {
            get {
                return ResourceManager.GetString("EN_UNSET_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unset top.
        /// </summary>
        internal static string EN_UNSET_TOP {
            get {
                return ResourceManager.GetString("EN_UNSET_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string EN_UPDATE {
            get {
                return ResourceManager.GetString("EN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не запускать вместе с OS.
        /// </summary>
        internal static string RU_ADD_AUTORUN {
            get {
                return ResourceManager.GetString("RU_ADD_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлено в автозапуск.
        /// </summary>
        internal static string RU_ADDED_AUTORUN {
            get {
                return ResourceManager.GetString("RU_ADDED_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автозапуск.
        /// </summary>
        internal static string RU_AUTORUN {
            get {
                return ResourceManager.GetString("RU_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        internal static string RU_CLOSE {
            get {
                return ResourceManager.GetString("RU_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запускать вместе с OS.
        /// </summary>
        internal static string RU_DELETE_AUTORUN {
            get {
                return ResourceManager.GetString("RU_DELETE_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалено из автозапуска.
        /// </summary>
        internal static string RU_DELETED_AUTORUN {
            get {
                return ResourceManager.GetString("RU_DELETED_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string RU_ERROR {
            get {
                return ResourceManager.GetString("RU_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть в меню задач.
        /// </summary>
        internal static string RU_HIDE_IN_TASKBAR {
            get {
                return ResourceManager.GetString("RU_HIDE_IN_TASKBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTopper свернут.
        /// </summary>
        internal static string RU_MINIMIZED {
            get {
                return ResourceManager.GetString("RU_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTopper свернут. Нажмите правой кнопкой на иконку снизу, чтобы открыть снова.
        /// </summary>
        internal static string RU_MINIMIZED_RIGHT_CLICK {
            get {
                return ResourceManager.GetString("RU_MINIMIZED_RIGHT_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступна новая версия, обновить сейчас?.
        /// </summary>
        internal static string RU_NEW_VERSION_AVAILABLE_QUESTION {
            get {
                return ResourceManager.GetString("RU_NEW_VERSION_AVAILABLE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установлена новейшая версия.
        /// </summary>
        internal static string RU_NO_UPDATE {
            get {
                return ResourceManager.GetString("RU_NO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string RU_OPEN {
            get {
                return ResourceManager.GetString("RU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный процесс больше не существует.
        /// </summary>
        internal static string RU_PROCESS_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("RU_PROCESS_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите процесс.
        /// </summary>
        internal static string RU_SELECT_PROCESS {
            get {
                return ResourceManager.GetString("RU_SELECT_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установите высоту и ширину окна.
        /// </summary>
        internal static string RU_SET_HEIGHT_WIDTH {
            get {
                return ResourceManager.GetString("RU_SET_HEIGHT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приоритет.
        /// </summary>
        internal static string RU_SET_THIS {
            get {
                return ResourceManager.GetString("RU_SET_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить выше.
        /// </summary>
        internal static string RU_SET_TOP {
            get {
                return ResourceManager.GetString("RU_SET_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не приоритет.
        /// </summary>
        internal static string RU_UNSET_THIS {
            get {
                return ResourceManager.GetString("RU_UNSET_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить ниже.
        /// </summary>
        internal static string RU_UNSET_TOP {
            get {
                return ResourceManager.GetString("RU_UNSET_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        internal static string RU_UPDATE {
            get {
                return ResourceManager.GetString("RU_UPDATE", resourceCulture);
            }
        }
    }
}
